gui:
 theme:
   inactiveBorderColor:
     - '#585273'
   optionsTextColor:
     - '#D4BFFF'
   selectedLineBgColor:
     - '#3E3859'
   selectedRangeBgColor:
     - '#2D2B40'
   cherryPickedCommitBgColor:
     - '#585273'
   cherryPickedCommitFgColor:
     - '#91DDFF'
   unstagedChangesColor:
     - '#F48FB1'
   defaultFgColor:
     - '#CBE3E7'
   searchingActiveBorderColor:
     - '#FFE6B3'
